### ISSUE TITLE
Exported styled-component with generic (Typescript) in styled function doesn't add props autocomplete when used in JSX

### ISSUE THREAD

**Issue by RIP21** [styled-components/webstorm-styled-components#58]
What steps will reproduce the problem?

1. 
Having let say this component:
```
import styled from 'styled-components'

const Component = styled.div<{ someProp: string }>``

export default Component
```
2.
```
import Component from 'components/Component'

const SomeOtherComponent = () => <Component />
```
3. Then trying to Ctrl + Space to autocomplete possible props.

What is the expected result?
Should suggest `someProp` in autocomplete

What happens instead?
No autocomplete.

**Comment by Havret** [comment]
+1

**Comment by undeadcat** [comment]
This is something that should be addressed on the IDE side. The relevant issue is https://youtrack.jetbrains.com/issue/WEB-34865.

**Comment by dagerikhl** [comment]
I think this is fixed, at least its status is set to fixed in the issue you linked @undeadcat, and I can't seem to replicate the bug.

**Comment by dagerikhl** [comment]
Actually IntelliJ, but I should think the tooling is the same. Using `IntelliJ IDEA 2018.3.1 (Ultimate Edition) Build #IU-183.4588.61, built on December 4, 2018`.

**Comment by prigara** [comment]
Hey all, the fix will land in WebStorm and IntelliJ IDEA 2018.3.3 which is expected at the end of December - beginning of January. Thank you for waiting!

**Comment by Havret** [comment]
Hey @prigara on your internal bug tracker this is marked as fixed, but the problem still remains. 

![image](https://user-images.githubusercontent.com/9103861/51330970-f3c9d800-1a78-11e9-9bc7-942b3582774d.png)

**Comment by prigara** [comment]
@halvves I've reopened the issue because it wasn't fixed for the latest version of `@types/styled-components`. Hope it will be fixed again soon. Thanks for bringing the attention to it.

**Comment by Havret** [comment]
@prigara It would be great if we have this fixed, because working with Webstorm and styled-components has been really painful for the last few months.

**Comment by undeadcat** [comment]
[WEB-34865](https://youtrack.jetbrains.com/issue/WEB-34865) is fixed for the newest styled-components versions on the IDE side in 2019.1. 
Please try it out in an EAP build (https://www.jetbrains.com/webstorm/eap/)
